apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

metadata:
  name: gitramakula-app

labels:
- includeSelectors: false
  includeTemplates: true
  pairs:
    managed-by: kustomize

resources:
- namespace.yaml
- configmap.yaml
- secrets.yaml
- postgres.yaml
- redis-commander.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml
- pdb.yaml
- redis-statefulset.yaml
- rabbitmq-statefulset.yaml
- kong-ingress.yaml

replicas:
- name: app-deployment
  count: 1

images:
- name: nginx
  newTag: latest

